# The base URL of the site.
base_url = "https://mothsart.github.io/"

# To avoid problems with some variables due to multilingual support,
# you will find repeated variables in the language section,
# it is recommended that you keep those of your language and the general
# ones with the same data.

default_language = "fr"
theme = "devlab"

# To find a detailed description of the following configuration variables
# you can go to https://www.getzola.org/documentation/getting-started/configuration/

output_dir = "public"

build_search_index = true
generate_feed = true
feed_filename = "rss.xml"
# feed_limit = 20

compile_sass = true

minify_html = false
hard_link_static = false

# ignored_content = []

title = "Le Labo du Nerd"
description = "Ce dev-blog-draft est celui d'un passionné du #numérique. Souvent dans la remise en question, rarement satisfait, en recherche de singularité. Ce site est avant-tout un réel banc d'essai : un labo ou je m'éclate et écrit au fil de l'eau mes essais... il n'a donc pas de délais de livraison."

taxonomies = [
    { name = "tags", rss = true, paginate_by = 5  },
    { name = "categories", rss = true, paginate_by = 5 }
]

[extra]
    author = "Jérémie Ferry @alias mothsart"

    # Use a square image (same height as width)
    avatar = "images/avatar.png"

    # To use a favicon convert your image to https://realfavicongenerator.net/,
    # then download and copy the package to static/images/favicon
    favicon = true
    locale = "fr_FR"
    message404 = "Tu t'es perdu mon ami ?"

    # dev uses Bootstrap icons,
    # you can go to https://icons.getbootstrap.com/ to find the full list
    [extra.menus]
        nav = [
            { name = "Accueil", url = "@/_index.md", icon = "bi-house", display = "block" },
            { name = "Devblog", url = "@/devblog/_index.md", icon = "bi-terminal", display = "block" },
            { name = "Réflexion", url = "@/reflexion/_index.md", icon = "bi bi-lightbulb", display = "block" },
            { name = "Recettes", url = "@/recieps/_index.md", icon = "bi-egg-fried", display = "block" },

            { name = "Recettes secretes", url = "@/secret/recettes/_index.md", display = "hidden" },
            { name = "Bricolage secret", url = "@/secret/bricolage/_index.md", display = "hidden" },
            { name = "Jardinage secret", url = "@/secret/jardinage/_index.md", display = "hidden" },

            { name = "Auteur", url = "@/author.md", icon = "bi-person", display = "block" },
            { name = "A propos", url = "@/about.md", icon = "bi-question-octagon", display = "block" }
        ]
    
    [extra.social]
        author_link = "https://mothsart.github.io/"
        twitter = "@user"
        links = [
            { name = "Email", url = "mailto:jerem.ferry@email.com", icon = "bi-envelope-fill" },
            { name = "GitHub", url = "https://github.com/mothsart", icon = "bi-github" },
            { name = "Twitter", url = "https://twitter.com/mothsart1", icon = "bi-twitter" },
        ]
    
    [extra.comments]
        disqus = "user"

    [extra.copyright]
        name = "CC BY 4.0"
        url = "https://creativecommons.org/licenses/by/4.0/"


[markdown]
    highlight_code = true
    highlight_theme = "gruvbox-dark"
    render_emoji = true
    external_links_target_blank = true
    external_links_no_follow = true
    external_links_no_referrer = true
    smart_punctuation = false


[search]
    include_title = true
    include_description = false
    include_path = false
    include_content = true
    # truncate_content_length = 100


[link_checker]
    # skip_prefixes = []
    # skip_anchor_prefixes = []

    internal_level = "error"
    external_level = "error"


[slugify]
    paths = "on"
    taxonomies = "on"
    anchors = "on"
